var compo = compo || {};
compo = {
		main : ()=>{
			return '<div id="wrap" class="main">'
			+'	<header id="header">'
			+'	</header>'
			+'	<!-- content -->'
			+'	<div id="contents">'
			+''
			+'	<div id="container" style="min-height: 0px;">'
			+'		<div class="content-header">'
			+'			<h2 class="header-title blind">여행일정 검색</h2>'
			+'			<div class="search-wrap">'
			+'				<div id="main_search_box" class="search-box">'
			+'					<form method="post" id="airSearchForm" name="airSearchForm">'
			+'						<!--  여행 타입 -->'
			+'						<input type="hidden" name="menu" id="menu" value="RT">'
			+'						<input type="hidden" name="trip" id="tripValue" value="RT">'
			+'						<!--  여행 타입 -->'
			+'						<!--  승객정보 -->'
			+'						<input type="hidden" name="adt" id="adt" value="1">'
			+'						<input type="hidden" name="chd" id="chd" value="0">'
			+'						<input type="hidden" name="inf" id="inf" value="0">'
			+'						<!--  승객정보 -->'
			+'						<!--  좌석 타입 -->'
			+'						<input type="hidden" name="comp_nm" id="comp_nm" value="일반석">'
			+'						<input type="hidden" name="comp" id="comp" value="Y">'
			+'						<input type="hidden" name="NewComp" id="NewComp" value="N"><!--프리미엄일반석의 경우만 Y-->'
			+'						<!--  좌석 타입 -->'
			+'						<!--  출발 도시 -->'
			+'						<input type="hidden" name="dep0" id="dep0">'
			+'						<input type="hidden" name="dep0_text" id="dep0_text">'
			+'						<input type="hidden" name="dep1" id="dep1">'
			+'						<input type="hidden" name="dep1_text" id="dep1_text">'
			+'						<input type="hidden" name="dep2" id="dep2">'
			+'						<input type="hidden" name="dep2_text" id="dep2_text">'
			+'						<input type="hidden" name="dep3" id="dep3">'
			+'						<input type="hidden" name="dep3_text" id="dep3_text">'
			+'						<!--  출발 도시 -->'
			+'						<!--  도착 도시 -->'
			+'						<input type="hidden" name="arr0" id="arr0">'
			+'						<input type="hidden" name="arr0_text" id="arr0_text">'
			+'						<input type="hidden" name="arr1" id="arr1">'
			+'						<input type="hidden" name="arr1_text" id="arr1_text">'
			+'						<input type="hidden" name="arr2" id="arr2">'
			+'						<input type="hidden" name="arr2_text" id="arr2_text">'
			+'						<input type="hidden" name="arr3" id="arr3">'
			+'						<input type="hidden" name="arr3_text" id="arr3_text">'
			+'						<!--  도착 도시 -->'
			+'						<!--  출발 날짜 -->'
			+'						<input type="hidden" name="depdate0" id="depdate0">'
			+'						<input type="hidden" name="depdate1" id="depdate1">'
			+'						<input type="hidden" name="depdate2" id="depdate2">'
			+'						<input type="hidden" name="depdate3" id="depdate3">'
			+'						<!--  출발 날짜 -->'
			+'						<!--  도착 날짜 -->'
			+'						<input type="hidden" name="retdate" id="retdate">'
			+'						<!--  도착 날짜 -->'
			+'						<!--  항공사 선택 -->'
			+'						<input type="hidden" name="prefCarArry" id="prefCarArry" value="ALL">'
			+'						<!--  항공사 선택 -->'
			+'						<!--  귀국일 미정 여부 -->'
			+'						<input type="hidden" name="returnUnfix" id="returnUnfix" value="N">'
			+'						<!--  귀국일 미정 여부 -->'
			+'						<!--  국내출발 여부-->'
			+'						<input type="hidden" name="startlocal" id="startlocal" value="Y">'
			+'						<!--  국내출발 여부 -->'
			+'						<!--  국제선 여부 -->'
			+'						<input type="hidden" name="startArea" id="startArea" value="Y">'
			+'						<!--  국제선 여부 -->'
			+'						<!-- 다구간 갯수 -->'
			+'						<input type="hidden" name="md_count" id="md_count" value="2">'
			+'						<!-- 다구간 갯수 -->'
									+''
			+'						<input type="hidden" name="dayInd" id="dayInd" value="N">'
			+'						<input type="hidden" name="daySeq" value="0"><!-- ? -->'
									+''
			+'						<input type="hidden" name="plusDate" id="plusDate">'
									+''
			+'						<input type="hidden" name="prefStsArry" id="prefStsArry" value="ALL">'
			+'						<input type="hidden" name="prefViaArry" id="prefViaArry" value="ALL">'
									+''
			+'						<input type="hidden" name="val" id="val">'
			+'						<input type="hidden" name="STEP" id="STEP">'
									+''
			+'						<input type="hidden" name="isBfm" id="isBfm" value="Y">'
			+'						<input type="hidden" id="mode" name="mode" value="v3"><!--skd_fare7 사용할때 넣는다  -->'
									+''
			+'						<input type="hidden" name="STEP" id="STEP">'
									+''
			+'						<div class="flight-type">'
			+'							<label class="fl-way-block is-return is-checked">'
			+'								<input type="radio" value="RT" name="RadioFlWay" class="radio-box" checked="checked">'
			+'								<span id="airport_01" class="radio-txt">왕복</span>'
			+'							</label>'
			+'							<label class="fl-way-block is-single">'
			+'								<input type="radio" value="OW" name="RadioFlWay" class="radio-box">'
			+'								<span id="airport_02" class="radio-txt">편도</span>'
			+'							</label>'
			+'							<label class="fl-way-block is-multi">'
			+'								<input type="radio" value="MD" name="RadioFlWay" class="radio-box">'
			+'								<span id="main_hotel_link" class="radio-txt">다구간</span>'
			+'							</label>'
			+'						</div>'
			+'						<div class="flight-field">'
			+'							<div class="flight-single active">'
			+'								<div class="fl-route">'
			+'									<div class="fl-item fl-field-from">'
			+'										<label class="fl-field-block">'
			+'											<span class="label-txt active">출발도시</span>'
			+'											<span class="input-con">'
															+'<input type="text" autocomplete="off" id="DepartureCity" name="DepartureCity" class="input-box pop-dep" placeholder="출발도시">'
			+'											</span>'
			+'										</label>'
			+'									</div>'
			+'									<div class="fl-swap"><a href="javascript:void(0)" onclick="swapCity()" class="btn btn-swap"></a></div>'
			+'									<div class="fl-item fl-field-to">'
			+'										<label class="fl-field-block">'
			+'											<span class="label-txt active">도착도시</span>'
			+'											<span class="input-con">'
															+'<input type="text" autocomplete="off" id="ArrivalCity" name="ArrivalCity" class="input-box pop-arr" placeholder="도착도시">'
			+'											</span>'
			+'										</label>'
			+'									</div>'
			+'								</div>'
			+'								<div class="fl-date t-datepicker">'
			+'									<div class="fl-item fl-field-depart">'
			+'										<div class="fl-field-block">'
			+'											<span class="label-txt active">가는날</span>'
			+'											<span class="input-con t-check-in"></span>'
			+'										</div>'
			+'									</div>'
			+'									<div class="fl-line"><i class="ico-line"></i></div>'
			+'									<div class="fl-item fl-field-return">'
			+'										<div class="fl-field-block">'
			+'											<span class="label-txt active">오는날</span>'
			+'											<span class="input-con t-check-out"></span>'
			+'										</div>'
			+'									</div>'
			+'									<div id="two-inputs" class="datepick round active">'
													+'<input id="date-range200" autocomplete="off" name="date" class="input-box" size="20" value="" placeholder="가는날" readonly="readonly">'
													+'<input id="date-range201" autocomplete="off" name="date" class="input-box" size="20" value="" placeholder="오는날" readonly="readonly">'
			+'									</div>'
			+'									<div class="datepick single">'
			+'										<input id="one-input" style="width:400px" size="40" autocomplete="off" value="" placeholder="가는날" readonly="">'
			+'									</div>'
			+'								</div>'
			+'							</div>'
			+'							<div class="flight-multi">'
			+'								<div class="multi-con-wrap">'
			+'									<div class="fl-multi-con">'
			+'										<div class="fl-route">'
			+'											<div class="fl-item fl-field-from">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity0" name="DepMultiCity0" class="input-box pop-dep" placeholder="출발도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
			+'											</div>'
			+'											<div class="fl-arrow"><i class="arrow-right"></i></div>'
			+'											<div class="fl-item fl-field-to">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity0" name="ArrMultiCity0" class="input-box pop-arr" placeholder="도착도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
			+'											</div>'
			+'										</div>'
			+'										<div class="fl-date t-datepicker">'
			+'											<div class="fl-item fl-field-depart">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt">가는날</span>'
			+'													<span class="input-con t-check-in"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="fl-item fl-field-return">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt active">오는날</span>'
			+'													<span class="input-con t-check-out"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="datepick multi">'
															+'<input id="multi-input0" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
			+'											</div>'
			+'											<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
			+'										</div>'
			+'									</div>'
			+'									<div class="fl-multi-con">'
			+'										<div class="fl-route">'
			+'											<div class="fl-item fl-field-from">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity1" name="DepMultiCity1" class="input-box pop-dep" placeholder="출발도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
			+'											</div>'
			+'											<div class="fl-arrow"><i class="arrow-right"></i></div>'
			+'											<div class="fl-item fl-field-to">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity1" name="ArrMultiCity1" class="input-box pop-arr" placeholder="도착도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
			+'											</div>'
			+'										</div>'
			+'										<div class="fl-date t-datepicker">'
			+'											<div class="fl-item fl-field-depart">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt">가는날</span>'
			+'													<span class="input-con t-check-in"></span>'
			+'												</div>'
															+''
			+'											</div>'
			+'											<div class="fl-item fl-field-return">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt active">오는날</span>'
			+'													<span class="input-con t-check-out"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="datepick multi">'
															+'<input id="multi-input1" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
			+'											</div>'
			+'											<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
			+'										</div>'
			+'									</div>'
			+'									<div class="fl-multi-con is-add add-item1"> <!-- 다구간이 2개 이상 추가되었을때 is-add 추가 -->'
			+'										<div class="fl-route">'
			+'											<div class="fl-item fl-field-from">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity2" name="DepMultiCity2" class="input-box pop-dep" placeholder="출발도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
			+'											</div>'
			+'											<div class="fl-arrow"><i class="arrow-right"></i></div>'
			+'											<div class="fl-item fl-field-to">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity2" name="ArrMultiCity2" class="input-box pop-arr" placeholder="도착도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
			+'											</div>'
			+'										</div>'
			+'										<div class="fl-date t-datepicker">'
			+'											<div class="fl-item fl-field-depart">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt">가는날</span>'
			+'													<span class="input-con t-check-in"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="fl-item fl-field-return">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt active">오는날</span>'
			+'													<span class="input-con t-check-out"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="datepick multi">'
															+'<input id="multi-input2" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
			+'											</div>'
			+'											<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
			+'										</div>'
			+'										<a href="javascript:void(0)" class="fl-con-remove" id="itemRemove01"><i class="btn btn-remove"></i></a>'
			+'									</div>'
			+'									<div class="fl-multi-con is-add add-item2"> <!-- 다구간이 2개 이상 추가되었을때 is-add 추가 -->'
			+'										<div class="fl-route">'
			+'											<div class="fl-item fl-field-from">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity3" name="DepMultiCity3" class="input-box pop-dep" placeholder="출발도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
			+'											</div>'
			+'											<div class="fl-arrow"><i class="arrow-right"></i></div>'
			+'											<div class="fl-item fl-field-to">'
			+'												<label class="fl-field-block">'
																+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity3" name="ArrMultiCity3" class="input-box pop-arr" placeholder="도착도시"></span>'
			+'												</label>'
			+'												<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
			+'											</div>'
			+'										</div>'
			+'										<div class="fl-date t-datepicker">'
			+'											<div class="fl-item fl-field-depart">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt">가는날</span>'
			+'													<span class="input-con t-check-in"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="fl-item fl-field-return">'
			+'												<div class="fl-field-block">'
			+'													<span class="label-txt active">오는날</span>'
			+'													<span class="input-con t-check-out"></span>'
			+'												</div>'
			+'											</div>'
			+'											<div class="datepick multi">'
															+'<input id="multi-input3" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
			+'											</div>'
			+'											<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
			+'										</div>'
			+'										<a href="javascript:void(0)" class="fl-con-remove" id="itemRemove02"><i class="btn btn-remove"></i></a>'
			+'									</div>'
			+'								</div>'
			+'								<div class="multi-add-wrap">'
			+'									<div class="fl-multi-add"><a href="javascript:void(0)" class="more-multi"><i class="xi-plus"></i> 다른 여정 추가</a></div>'
			+'								</div>'
			+'							</div>'
			+'						</div>'
			+'						<div class="insert" style="position: absolute;right: 10px;top: 0px;">'
										+'<span class="dcheck-block" id="directClick"><input type="checkbox" id="directCheck" value="0" name="directCheck"> <label class="label">직항만</label></span>'
			+'						</div>'
			+'						<div class="flight-search">'
										+''
			+'							<div class="fl-item fl-field-option">'
			+'								<label class="fl-field-block">'
			+'									<span class="label-txt">승객, 좌석등급</span>'
			+'									<span class="input-con">'
													+'<input type="text" id="passenger_value" autocomplete="off" readonly="readonly" class="input-box pop-search" value="성인 1, 일반석">'
			+'									</span>'
			+'								</label>'
			+'							</div>'
										+'<button id="main_search_btn" type="button" class="btn btn-search" id="btnSearch"><i class="ico-pin-white"></i><span>검색</span></button>'
			+'						</div>'
			+'					</form>'
			+'				</div>'
			+'				<div id="check_btn01" class="oneway-validation" id="notmdalert" style="height:22px"> <!--왕복/편도용-->'
			+'					<div class="fl" ><p class="alert-danger" style="visibility:hidden">출발도시 코멘트입니다..</p></div>'
			+'					<div class="fl"><p class="alert-danger" style="visibility:hidden">도착도시 코멘트입니다.</p></div>'
			+'					<div class="fl"><p class="alert-danger" style="visibility:hidden">가는날 코멘트입니다.</p></div>'
			+'					<div class="fl"><p class="alert-danger" style="visibility:hidden">오늘날 코멘트입니다.</p></div>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	<div id="bx-pager02" class="bx-controls"></div>'
			+'		</div>'
			+'		<section id="qusghk" class="main-howto">'
			+'			<div class="main-type">'
			+'				<dl>'
			+'					<dt id="main_text_01">투어비스 이용방법</dt>'
			+'					<dd id="main_text_02">투어비스가 처음이신가요?<br>쉽고 편리한 투어비스 이용해 보세요.</dd>'
			+'				</dl>'
			+'			</div>'
			+'			<div class="main-step">'
			+'				<ul>'
			+'					<li>'
			+'						<span class="tit">STEP 1</span>'
			+'						<span class="sub">요금을 선택하고</span>'
			+'					</li>'
			+'					<li>'
			+'						<span class="tit">STEP 2</span>'
			+'						<span class="sub">탑승객 정보를 입력하고</span>'
			+'					</li>'
			+'					<li>'
			+'						<span class="tit">STEP 3</span>'
			+'						<span class="sub">결제를 하면</span>'
			+'					</li>'
			+'					<li>'
			+'						<span class="tit">STEP 4</span>'
			+'						<span class="sub">발권 완료</span>'
			+'					</li>'
			+'				</ul>'
			+'			</div>'
			+'		</section>'
			+'	</div>'
			+''
			+'<div class="page-layer" id="layer-route-02" style="position:absolute;left:0">'
			+'	<div class="layer-wrap">'
			+'		<div class="con-wrap">'
			+'			<form class="search-wrap">'
			+'				<fieldset class="city-search">'
			+'					<legend>도시검색</legend>'
			+'					<div class="search-step step-02" id="searchCityList">'
									+''
			+'					</div>'
			+'				</fieldset>'
			+'			</form>'
			+'		</div>'
			+'		<a href="javascript:void(0);" class="btn-close"></a>'
			+'	</div>'
			+'</div>'
			+''
			+'<div class="page-layer" id="layer-search" style="height:500px">'
			+'	<div class="layer-wrap">'
			+'		<div class="con-wrap">'
			+'			<form class="seat-wrap">'
			+'				<fieldset class="seat-option">'
			+'					<div class="counter-wrap">'
			+'						<div class="counter-box">'
			+'							<div class="counter-item">'
			+'								<div class="label-con">'
			+'									<span class="count-label">성인</span>'
			+'									<span class="count-desc">(만 12세 이상)</span>'
			+'								</div>'
			+'								<div class="count-con">'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="adultm"><i class="ico-minus1"></i></a>'
			+'									<span class="option-num"><input type="text" value="1" id="adt_value" readonly=""></span>'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="adultp"><i class="ico-plus1"></i></a>'
			+'								</div>'
			+'							</div>'
			+'							<div class="counter-item">'
			+'								<div class="label-con">'
			+'									<span class="count-label">아동</span>'
			+'									<span class="count-desc">(만 2 - 12세)</span>'
			+'								</div>'
			+'								<div class="count-con">'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="childm"><i class="ico-minus1"></i></a>'
			+'									<span class="option-num"><input type="text" value="0" id="chd_value" class="disable" readonly=""></span>'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="childp"><i class="ico-plus1"></i></a>'
			+'								</div>'
			+'							</div>'
			+'							<div class="counter-item">'
			+'								<div class="label-con">'
			+'									<span class="count-label">유아</span>'
			+'									<span class="count-desc">(만 2세 이하)</span>'
			+'								</div>'
			+'								<div class="count-con">'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="infuntm"><i class="ico-minus1"></i></a>'
			+'									<span class="option-num"><input type="text" value="0" id="inf_value" class="disable" readonly=""></span>'
			+'									<a href="javascript:void(0)" class="btn-count" ptype="infuntp"><i class="ico-plus1"></i></a>'
			+'								</div>'
			+'							</div>'
			+'						</div>'
			+'						<p class="alert-notice" style="text-align:center">성인, 아동, 유아의 나이는 탑승일 기준입니다.</p>'
			+'						<p id="psgdanger" class="alert-danger blind"></p>'
			+'					</div>'
			+'					<div class="radio-area seat-item">'
			+'						<label class="fl-seat-block is-checked" value="Y">'
			+'							<a href="javascript:void(0)" class="radio-txt">일반석</a>'
			+'						</label>'
			+'						<label class="fl-seat-block" value="P">'
			+'							<a href="javascript:void(0)" class="radio-txt">프리미엄 일반석</a>'
			+'						</label>'
			+'						<label class="fl-seat-block" value="C">'
			+'							<a href="javascript:void(0)" class="radio-txt">비즈니스석</a>'
			+'						</label>'
			+'						<label class="fl-seat-block" value="F">'
			+'							<a href="javascript:void(0)" class="radio-txt">일등석</a>'
			+'						</label>'
			+'					</div>'
			+'				</fieldset>'
			+'			</form>'
			+'		</div>'
			+'		<a href="javascript:void(0);" class="btn-close"></a>'
			+'	</div>'
			+'</div>'
			+''
			+'	<div class="popup pop-cont" id="new-loading-bar" style="position: fixed; left: 50%; top: 40%; margin-left: -600px; margin-top: -857px;">'
			+'		<div class="loading-box">'
			+'			<img id="newLoadImg" src="https://www.tourvis.com/resource_pc/images/tvsloading.gif">'
			+'			<p class="mt-15" id="loading-text"></p>'
			+'		</div>'
			+'	</div>'
			+'</div>';
		},
		search_airport_result_bottom:()=>{
			return '<div class="content">'
	        +'<div class="lookup-result">'
	        +'<div class="fl">'
	                +'<div class="search-result">검색결과: 총 <span class="bold" id="totalFare">37</span>건</div>'
	                +'<span class="trip">'
	                        +'<span class="from" id="listFrom">인천</span>'
	                        +'<i class="xi-long-arrow-right"></i>'
	                        +'<span class="to" id="listTo">뉴욕</span>'
	                +'</span>'
	                +'<span id="listDateTxt">2019년 4월 26일 금요일</span>'
	        +'</div>'
	        +'<div class="fr mt-10">'
	                +'<span style="font-size:12px;color:#999;font-weight:400;">* 요금은 1인당 운임이며, 유류할증료와 제세공과금을 포함한 금액입니다.</span>'
	        +'</div>'
	+'</div>'
	+'<div class="sort-tab">'
	        +'<ul id="sortTab">'
	        +'<li><span class="tooltip-recomm">추천 <i class="xi-info"></i></span><span id="recprice">1,300,200원</span><div id="recpriceWr" class="loading_txt" style="display:none"></div></li>'
	                +'<li class="active"><span>최저가</span><span id="lowprice">1,276,900원</span><div id="lowpriceWr" class="loading_txt" style="display:none"></div></li>'
	                +'<li><span>최단시간</span><span id="timeprice">1,577,500원</span><div id="timepriceWr" class="loading_txt" style="display:none"></div></li>'
	                +'<li><span>이른출발</span><span id="depprice">1,871,100원</span><div id="deppriceWr" class="loading_txt" style="display:none"></div></li>'
	                +'<li><span>이른도착</span><span id="arrprice">1,422,100원</span><div id="arrpriceWr" class="loading_txt" style="display:none"></div></li>'
	        +'</ul>'
	+'</div>'
	+'<input type="hidden" id="titleClsName" value="일반석">'
	+'<div class="lookup-cont faq-cont tab-cont">'
	        +'<ul class="list-view faq-list" id="airOfferList">'
	+'        '
	+'                '
	+'<li>'
	+'<div class="list-head question table-st" fareindex="171">'
	+'<div class="cell-left flight-name">'
	+'<span class="air-logo">'
	+'<img src="/resource_pc/images/logo/KE.png" airlogo="1">'
	+'</span>'
	+'<span class="air-info">'
	+'<span class="air-name ">대한항공   </span>'
	+'                                        '
	+'<span class="air-num" style="max-width: 200px;">KE7273 / 델타항공에서 공동운항</span>'
	+'<span class="air-num" style="max-width: 200px;">DL3403 / ENDEAVOR AIR DBA DELTA CONNECTION에서 공동운항</span>'
	+'</span>'
	+'</div>'
	+'<div class="cell-center flight-time">'
	+'<div class="time-box depart">'
	+'<span class="code">ICN</span>'
	+'<span class="time">10:35</span>'
	+'</div>'
	+'<div class="time-box flight-img">'
	+'<span class="total-time">1회 경유</span>'
	+'                                        '
	+'<span class="airport">DTW</span>'
	+'                                        '
	+'<span class="air-img"></span>'
	+'<div class="air-info-box" style="">'
	+'                                        '
	+'                                        '
	+'디트로이트에서 환승 1시간 21분<br>'
	+'</div>'
	+'</div>'
	+'<div class="time-box arrive">'
	+'<span class="code">JFK</span>'
	+'<span class="time">13:59</span>'
	+'</div>'
	+'</div>'
	+'<div class="cell-center" style="color:#999;font-size:12px;width:13%;text-align:left;">16시간 24분 소요'
	+'<br>'
	+'<a href="javascript:void(0)" onclick="moveBaggagePage(event,&quot;https://ko.delta.com/content/www/en_US/traveling-with-us/baggage/before-your-trip/checked.html#StandardCheckedBagAllowance&quot;)" class="btn-text" style="font-size:12px;">무료 수하물 2 개</a>'
	+'</div>'
	+'<div class="cell-right trip-price">'
	+'<div>'
	+'<span class="blue">1,797,400</span>원'
	+'<div class="price-info-box" style="display: block; opacity: 0;">'
	+'<div class="total-price-info">'
	+'<dl class="table-st">'
	        +'<dt>'
	                +'<span class="cell-left">성인 항공권</span>'
	                +'<span class="cell-right">1,797,400<span class="unit">원</span></span>'
	                +'<span class="cell-right">X 1</span>'
	        +'</dt>'
	        +'<dd>'
	                +'<span class="cell-left">항공권료</span>'
	                +'<span class="cell-right">1,557,200원</span>'
	                +'<span class="cell-right"></span>'
	        +'</dd>'
	        +'<dd>'
	                +'<span class="cell-left">유류할증료</span>'
	                +'<span class="cell-right">122,400원</span>'
	                +'<span class="cell-right"></span>'
	        +'</dd>'
	        +'<dd>'
	                +'<span class="cell-left">제세공과금</span>'
	                +'<span class="cell-right">107,800원</span>'
	                +'<span class="cell-right"></span>'
	        +'</dd>'
	        +'<dd>'
	                +'<span class="cell-left">발권대행료</span>'
	                +'<span class="cell-right">10,000원</span>'
	                +'<span class="cell-right"></span>'
	        +'</dd>'
	+'</dl>'
	+'</div>'
	+'<div class="table-st total-price-sum">'
	+'<div class="cell-left">총 요금</div>'
	+'<div class="cell-right trip-price">'
	        +'<span class="blue">1,797,400</span>'
	        +'<span>원</span>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<div id="modify_icon01" class="cell-right expand-icon">'
	+'<i class="xi-angle-down-min"></i>'
	+'<i class="xi-angle-up-min"></i>'
	+'</div>'
	+'</div>'
	+'<div class="list-body answer">'
	+'<div class="body-wrap">'
	+'<div class="trip-item table-st first-item">'
	+'<div class="cell-left date">4월 26일(금)</div>'
	+'<div class="cell-right flight-time">13시간 9분</div>'
	+'<div class="item-info">'
	+'<div class="summary">'
	+'<span class="air-logo-22"><img src="/resource_pc/images/logo/KE.png" airlogo="1"></span>'
	+'<span class="duration">10:35 - 10:44 </span>'
	+'<span class="trip">'
	        +'<span class="from">ICN 인천 T2</span>'
	        +'<i class="xi-long-arrow-right"></i>'
	        +'<span class="to">DTW 디트로이트 TEM</span>'
	+'</span>'
	+'</div>'
	+'<div class="detail">'
	+'<span>대한항공</span>'
	+'<span>KE7273</span>'
	+'<span>Airbus A359</span>'
	+'<span>델타항공에서 공동운항 DL0158</span>'
	+'<span>일반석</span>'
	+'</div>'
	+'</div>'
	+'<div class="cell-left transfer">디트로이트에서 환승</div>'
	+'<div class="cell-right transfer-time">1시간 21분</div>'
	+'</div>'
	+'<div class="trip-item table-st last-item">'
	+'<div class="cell-left date">4월 26일(금)</div>'
	+'<div class="cell-right flight-time">1시간 54분</div>'
	+'<div class="item-info">'
	+'<div class="summary">'
	+'<span class="air-logo-22"><img src="/resource_pc/images/logo/DL.png" airlogo="1"></span>'
	+'<span class="duration">12:05 - 13:59 </span>'
	+'<span class="trip">'
	        +'<span class="from">DTW 디트로이트 TEM</span>'
	        +'<i class="xi-long-arrow-right"></i>'
	        +'<span class="to">JFK 뉴욕(JFK공항) T4</span>'
	+'</span>'
	+'</div>'
	+'<div class="detail">'
	+'<span>델타항공</span>'
	+'<span>DL3403</span>'
	+'<span>CR9</span>'
	+'<span>ENDEAVOR AIR DBA DELTA CONNECTION에서 공동운항 DL3403</span>'
	+'<span>일반석</span>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<div class="result-wrap">'
	+'<ul class="result-item ">'
	+'<li class="type">일반석 - 성인(삼성2v3카드) </li>'
	+'<li><a href="javascript:void(0)" class="btn small type03 btn-choice" onclick="selectFare(171, 0, 3150016)">선택</a></li>'
	+'<li class="rate trip-price">'
	+'<span class="notbook">잔여</span> <span class="notbook-num ">6</span><span class="notbook">석</span><br>'
	+'<div>1,797,400<span class="small-text">원</span>'
	+'<div class="price-info-box" style="display: block; opacity: 0;">'
	        +'<div class="total-price-info">'
	                +'<dl class="table-st">'
	                        +'<dt>'
	                                +'<span class="cell-left">성인 항공권</span>'
	                                +'<span class="cell-right">1,797,400<span class="unit">원</span></span>'
	                                +'<span class="cell-right">X 1</span>'
	                        +'</dt>'
	                        +'<dd>'
	                                +'<span class="cell-left">항공권료</span>'
	                                +'<span class="cell-right">1,557,200원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">유류할증료</span>'
	                                +'<span class="cell-right">122,400원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">제세공과금</span>'
	                                +'<span class="cell-right">107,800원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">발권대행료</span>'
	                                +'<span class="cell-right">10,000원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                +'</dl>'
	        +'</div>'
	        +'<div class="table-st total-price-sum">'
	                +'<div class="cell-left">총 요금</div>'
	                +'<div class="cell-right trip-price">'
	                        +'<span class="blue">1,797,400</span>'
	                        +'<span>원</span>'
	                +'</div>'
	        +'</div>'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li class="seat"><a href="javascript:void(0)" class="btn-text" onclick="openFareRule(171, 0, 3150016)"><i class="xi-info-o"></i> 요금규정</a></li>'
	+'</ul><br class="clear">'
	+'<ul class="result-item ">'
	+'<li class="type">일반석 - 삼성카드 </li>'
	+'<li><a href="javascript:void(0)" class="btn small type03 btn-choice" onclick="selectFare(171, 0, 2520024)">선택</a></li>'
	+'<li class="rate trip-price">'
	+'<span class="notbook">잔여</span> <span class="notbook-num ">6</span><span class="notbook">석</span><br>'
	+'<div>1,833,800<span class="small-text">원</span>'
	+'<div class="price-info-box" style="display: block; opacity: 0;">'
	        +'<div class="total-price-info">'
	                +'<dl class="table-st">'
	                        +'<dt>'
	                                +'<span class="cell-left">성인 항공권</span>'
	                                +'<span class="cell-right">1,833,800<span class="unit">원</span></span>'
	                                +'<span class="cell-right">X 1</span>'
	                        +'</dt>'
	                        +'<dd>'
	                                +'<span class="cell-left">항공권료</span>'
	                                +'<span class="cell-right">1,593,600원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">유류할증료</span>'
	                                +'<span class="cell-right">122,400원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">제세공과금</span>'
	                                +'<span class="cell-right">107,800원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">발권대행료</span>'
	                                +'<span class="cell-right">10,000원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                +'</dl>'
	        +'</div>'
	        +'<div class="table-st total-price-sum">'
	                +'<div class="cell-left">총 요금</div>'
	                +'<div class="cell-right trip-price">'
	                        +'<span class="blue">1,833,800</span>'
	                        +'<span>원</span>'
	                +'</div>'
	        +'</div>'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li class="seat"><a href="javascript:void(0)" class="btn-text" onclick="openFareRule(171, 0, 2520024)"><i class="xi-info-o"></i> 요금규정</a></li>'
	+'</ul><br class="clear">'
	+'<ul class="result-item " style="">'
	+'<li class="type">일반석 - 일반요금 </li>'
	+'<li><a>선택</a></li>'
	+'<li class="rate trip-price">'
	+'<span class="notbook">잔여</span> <span class="notbook-num ">6</span><span class="notbook">석</span><br>'
	+'<div>1,891,500<span class="small-text">원</span>'
	+'<div class="price-info-box" style="display: block; opacity: 0;">'
	        +'<div class="total-price-info">'
	                +'<dl class="table-st">'
	                        +'<dt>'
	                                +'<span class="cell-left">성인 항공권</span>'
	                                +'<span class="cell-right">1,891,500<span class="unit">원</span></span>'
	                                +'<span class="cell-right">X 1</span>'
	                        +'</dt>'
	                        +'<dd>'
	                                +'<span class="cell-left">항공권료</span>'
	                                +'<span class="cell-right">1,651,300원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">유류할증료</span>'
	                                +'<span class="cell-right">122,400원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">제세공과금</span>'
	                                +'<span class="cell-right">107,800원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                        +'<dd>'
	                                +'<span class="cell-left">발권대행료</span>'
	                                +'<span class="cell-right">10,000원</span>'
	                                +'<span class="cell-right"></span>'
	                        +'</dd>'
	                +'</dl>'
	        +'</div>'
	        +'<div class="table-st total-price-sum">'
	                +'<div class="cell-left">총 요금</div>'
	                +'<div class="cell-right trip-price">'
	                        +'<span class="blue">1,891,500</span>'
	                        +'<span>원</span>'
	                +'</div>'
	        +'</div>'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li><i class="xi-info-o"></i> 요금규정</a></li>'
	+'</ul><br class="clear">'
	+'</div>'
	+'</div>'
	+'</li>'
	+'</ul>'
	        +'<br class="clear">'
	+'</div>'
	+'<h2 style="display:none" id="otherTitle" class="dark normal-weight mt-40">다른 요금 항공편 선택 <span class="normal-text">다른 요금의 항공편을 선택하면 전체 여정의 요금과 규정이 변경됩니다.</span></h2>'
	+'<div class="lookup-cont faq-cont tab-cont mt-10" id="returnOfferList" style="display:none">'
	        +'<ul class="list-view faq-list" id="airOfferListSE"></ul>'
	+'</div>'
	+'<div class="content-not" id="noDatas" style="display:none">'
	        +'<span><img src="/resource_pc/images/common/filter_not.png" alt=""></span>'
	        +'<p>검색 결과가 없습니다.</p>'
	        +'<p>검색 조건 변경 후 다시 시도하세요.</p>'
	+'</div>'
	+'</div>'
		},
	
	hotel_top:()=>{
		return '<header id="header">'
		+'</header>'
		+'<!-- content -->'
		+'<div id="contents">'
		+''
		+'<div id="container" style="min-height: 159px;">'
		+'<div class="content-header">'
		+'<h2 class="header-title blind">여행일정 검색</h2>'
		+'<div class="search-wrap">'
		+'<div id="main_search_result1" class="search-box">'
		+'<form method="post" id="airSearchForm" name="airSearchForm">'
		+'<!--  여행 타입 -->'
		+'<input type="hidden" name="menu" id="menu" value="RT">'
		+'<input type="hidden" name="trip" id="tripValue" value="RT">'
		+'<!--  여행 타입 -->'
		+'<!--  승객정보 -->'
		+'<input type="hidden" name="adt" id="adt" value="1">'
		+'<input type="hidden" name="chd" id="chd" value="0">'
		+'<input type="hidden" name="inf" id="inf" value="0">'
		+'<!--  승객정보 -->'
		+'<!--  좌석 타입 -->'
		+'<input type="hidden" name="comp_nm" id="comp_nm" value="일반석">'
		+'<input type="hidden" name="comp" id="comp" value="Y">'
		+'<input type="hidden" name="NewComp" id="NewComp" value="N"><!--프리미엄일반석의 경우만 Y-->'
		+'<!--  좌석 타입 -->'
		+'<!--  출발 도시 -->'
		+'<input type="hidden" name="dep0" id="dep0">'
		+'<input type="hidden" name="dep0_text" id="dep0_text">'
		+'<input type="hidden" name="dep1" id="dep1">'
		+'<input type="hidden" name="dep1_text" id="dep1_text">'
		+'<input type="hidden" name="dep2" id="dep2">'
		+'<input type="hidden" name="dep2_text" id="dep2_text">'
		+'<input type="hidden" name="dep3" id="dep3">'
		+'<input type="hidden" name="dep3_text" id="dep3_text">'
		+'<!--  출발 도시 -->'
		+'<!--  도착 도시 -->'
		+'<input type="hidden" name="arr0" id="arr0">'
		+'<input type="hidden" name="arr0_text" id="arr0_text">'
		+'<input type="hidden" name="arr1" id="arr1">'
		+'<input type="hidden" name="arr1_text" id="arr1_text">'
		+'<input type="hidden" name="arr2" id="arr2">'
		+'<input type="hidden" name="arr2_text" id="arr2_text">'
		+'<input type="hidden" name="arr3" id="arr3">'
		+'<input type="hidden" name="arr3_text" id="arr3_text">'
		+'<!--  도착 도시 -->'
		+'<!--  출발 날짜 -->'
		+'<input type="hidden" name="depdate0" id="depdate0">'
		+'<input type="hidden" name="depdate1" id="depdate1">'
		+'<input type="hidden" name="depdate2" id="depdate2">'
		+'<input type="hidden" name="depdate3" id="depdate3">'
		+'<!--  출발 날짜 -->'
		+'<!--  도착 날짜 -->'
		+'<input type="hidden" name="retdate" id="retdate">'
		+'<!--  도착 날짜 -->'
		+'<!--  항공사 선택 -->'
		+'<input type="hidden" name="prefCarArry" id="prefCarArry" value="ALL">'
		+'<!--  항공사 선택 -->'
		+'<!--  귀국일 미정 여부 -->'
		+'<input type="hidden" name="returnUnfix" id="returnUnfix" value="N">'
		+'<!--  귀국일 미정 여부 -->'
		+'<!--  국내출발 여부-->'
		+'<input type="hidden" name="startlocal" id="startlocal" value="Y">'
		+'<!--  국내출발 여부 -->'
		+'<!--  국제선 여부 -->'
		+'<input type="hidden" name="startArea" id="startArea" value="Y">'
		+'<!--  국제선 여부 -->'
		+'<!-- 다구간 갯수 -->'
		+'<input type="hidden" name="md_count" id="md_count" value="2">'
		+'<!-- 다구간 갯수 -->'
		+''
		+'<input type="hidden" name="dayInd" id="dayInd" value="N">'
		+'<input type="hidden" name="daySeq" value="0"><!-- ? -->'
		+''
		+'<input type="hidden" name="plusDate" id="plusDate">'
		+''
		+'<input type="hidden" name="prefStsArry" id="prefStsArry" value="ALL">'
		+'<input type="hidden" name="prefViaArry" id="prefViaArry" value="ALL">'
		+''
		+'<input type="hidden" name="val" id="val">'
		+'<input type="hidden" name="STEP" id="STEP">'
		+''
		+'<input type="hidden" name="isBfm" id="isBfm" value="Y">'
		+'<input type="hidden" id="mode" name="mode" value="v3"><!--skd_fare7 사용할때 넣는다  -->'
		+''
		+'<input type="hidden" name="STEP" id="STEP">'
		+''
		+'<div class="flight-type">'
		+'<label class="fl-way-block is-return is-checked">'
		+'<input type="radio" value="RT" name="RadioFlWay" class="radio-box" checked="checked">'
		+'<span id="hotel_main_icon" class="radio-txt">왕복</span>'
		+'</label>'
		+'<label class="fl-way-block is-single">'
		+'<input type="radio" value="OW" name="RadioFlWay" class="radio-box">'
		+'<span id="new_hotel_search_text" class="radio-txt">편도</span>'
		+'</label>'
		+'<label class="fl-way-block is-multi">'
		+'<input type="radio" value="MD" name="RadioFlWay" class="radio-box">'
		+'<span id="main_hotel_link" class="radio-txt">다구간</span>'
		+'</label>'
		+'</div>'
		+'<div class="flight-field">'
		+'<div class="flight-single active">'
		+'<div class="fl-route">'
		+'<div class="fl-item fl-field-from">'
		+'<label class="fl-field-block">'
		+'<span class="label-txt active">출발도시</span>'
		+'<span class="input-con">'
		+'<input type="text" autocomplete="off" id="DepartureCity" name="DepartureCity" class="input-box pop-dep" placeholder="출발도시">'
		+'</span>'
		+'</label>'
		+'</div>'
		+'<div class="fl-swap"><a href="javascript:void(0)" onclick="swapCity()" class="btn btn-swap"></a></div>'
		+'<div class="fl-item fl-field-to">'
		+'<label class="fl-field-block">'
		+'<span id="night_destination" class="label-txt active">도착도시</span>'
		+'<span class="input-con">'
		+'<input type="text" autocomplete="off" id="ArrivalCity" name="ArrivalCity" class="input-box pop-arr" placeholder="숙박도시">'
		+'</span>'
		+'</label>'
		+'</div>'
		+'</div>'
		+'<div class="fl-date t-datepicker">'
		+'<div class="fl-item fl-field-depart">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">가는날</span>'
		+'<span class="input-con t-check-in"></span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-line"><i class="ico-line"></i></div>'
		+'<div class="fl-item fl-field-return">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">오는날</span>'
		+'<span class="input-con t-check-out"></span>'
		+'</div>'
		+'</div>'
		+'<div id="two-inputs" class="datepick round active">'
		+'<input id="date-range200" name="date1" autocomplete="off" class="input-box" size="20" value="" placeholder="가는날" readonly="readonly">'
		+'<input id="date-range201" autocomplete="off" class="input-box" size="20" value="" placeholder="오는날" readonly="readonly">'
		+'</div>'
		+'<div class="datepick single">'
		+'<input id="one-input" style="width:400px" size="40" autocomplete="off" value="" placeholder="가는날" readonly="">'
		+'</div>'
		+'</div>'
		+'</div>'
		+'<div class="flight-multi">'
		+'<div class="multi-con-wrap">'
		+'<div class="fl-multi-con">'
		+'<div class="fl-route">'
		+'<div class="fl-item fl-field-from">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity0" name="DepMultiCity0" class="input-box pop-dep" placeholder="출발도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
		+'</div>'
		+'<div class="fl-arrow"><i class="arrow-right"></i></div>'
		+'<div class="fl-item fl-field-to">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity0" name="ArrMultiCity0" class="input-box pop-arr" placeholder="도착도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-date t-datepicker">'
		+'<div class="fl-item fl-field-depart">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt">가는날</span>'
		+'<span class="input-con t-check-in"></span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-item fl-field-return">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">오는날</span>'
		+'<span class="input-con t-check-out"></span>'
		+'</div>'
		+'</div>'
		+'<div class="datepick multi">'
		+'<input id="multi-input0" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
		+'</div>'
		+'<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-multi-con">'
		+'<div class="fl-route">'
		+'<div class="fl-item fl-field-from">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity1" name="DepMultiCity1" class="input-box pop-dep" placeholder="출발도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
		+'</div>'
		+'<div class="fl-arrow"><i class="arrow-right"></i></div>'
		+'<div class="fl-item fl-field-to">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity1" name="ArrMultiCity1" class="input-box pop-arr" placeholder="도착도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-date t-datepicker">'
		+'<div class="fl-item fl-field-depart">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt">가는날</span>'
		+'<span class="input-con t-check-in"></span>'
		+'</div>'
		+''
		+'</div>'
		+'<div class="fl-item fl-field-return">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">오는날</span>'
		+'<span class="input-con t-check-out"></span>'
		+'</div>'
		+'</div>'
		+'<div class="datepick multi">'
		+'<input id="multi-input1" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
		+'</div>'
		+'<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-multi-con is-add add-item1"> <!-- 다구간이 2개 이상 추가되었을때 is-add 추가 -->'
		+'<div class="fl-route">'
		+'<div class="fl-item fl-field-from">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity2" name="DepMultiCity2" class="input-box pop-dep" placeholder="출발도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
		+'</div>'
		+'<div class="fl-arrow"><i class="arrow-right"></i></div>'
		+'<div class="fl-item fl-field-to">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity2" name="ArrMultiCity2" class="input-box pop-arr" placeholder="도착도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-date t-datepicker">'
		+'<div class="fl-item fl-field-depart">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt">가는날</span>'
		+'<span class="input-con t-check-in"></span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-item fl-field-return">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">오는날</span>'
		+'<span class="input-con t-check-out"></span>'
		+'</div>'
		+'</div>'
		+'<div class="datepick multi">'
		+'<input id="multi-input2" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
		+'</div>'
		+'<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
		+'</div>'
		+'<a href="javascript:void(0)" class="fl-con-remove" id="itemRemove01"><i class="btn btn-remove"></i></a>'
		+'</div>'
		+'<div class="fl-multi-con is-add add-item2"> <!-- 다구간이 2개 이상 추가되었을때 is-add 추가 -->'
		+'<div class="fl-route">'
		+'<div class="fl-item fl-field-from">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="DepMultiCity3" name="DepMultiCity3" class="input-box pop-dep" placeholder="출발도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">출발도시 코멘트입니다.</span>'
		+'</div>'
		+'<div class="fl-arrow"><i class="arrow-right"></i></div>'
		+'<div class="fl-item fl-field-to">'
		+'<label class="fl-field-block">'
		+'<span class="input-con"><input autocomplete="off" type="text" id="ArrMultiCity3" name="ArrMultiCity3" class="input-box pop-arr" placeholder="도착도시"></span>'
		+'</label>'
		+'<span class="validation-comment" style="visibility: hidden;">도착도시 코멘트입니다.</span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-date t-datepicker">'
		+'<div class="fl-item fl-field-depart">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt">가는날</span>'
		+'<span class="input-con t-check-in"></span>'
		+'</div>'
		+'</div>'
		+'<div class="fl-item fl-field-return">'
		+'<div class="fl-field-block">'
		+'<span class="label-txt active">오는날</span>'
		+'<span class="input-con t-check-out"></span>'
		+'</div>'
		+'</div>'
		+'<div class="datepick multi">'
		+'<input id="multi-input3" style="width:400px" autocomplete="off" size="40" value="" placeholder="가는날" readonly="readonly">'
		+'</div>'
		+'<span class="validation-comment" style="visibility: hidden;">가는날 코멘트입니다.</span>'
		+'</div>'
		+'<a href="javascript:void(0)" class="fl-con-remove" id="itemRemove02"><i class="btn btn-remove"></i></a>'
		+'</div>'
		+'</div>'
		+'<div class="multi-add-wrap">'
		+'<div class="fl-multi-add"><a href="javascript:void(0)" class="more-multi"><i class="xi-plus"></i> 다른 여정 추가</a></div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'<div class="insert" style="position: absolute;right: 10px;top: 0px;">'
		+'<span class="dcheck-block" id="directClick"><input type="checkbox" id="directCheck" value="0" name="directCheck"> <label id="hotel_oneway" class="label">직항만</label></span>'
		+'</div>'
		+'<div class="flight-search">'
		+''
		+'<div class="fl-item fl-field-option">'
		+'<label class="fl-field-block">'
		+'<span class="label-txt">승객, 좌석등급</span>'
		+'<span class="input-con">'
		+'<input type="text" id="passenger_value" autocomplete="off" readonly="readonly" class="input-box pop-search" value="성인 1, 일반석">'
		+'</span>'
		+'</label>'
		+'</div>'
		+'<button id="main_hotel_search_btn" type="button" class="btn btn-search" id="btnSearch"><i class="ico-pin-white"></i><span>검색</span></button>'
		+'</div>'
		+'</form>'
		+'</div>'
		+'<div class="oneway-validation" id="notmdalert" style="height:22px"> <!--왕복/편도용-->'
		+'<div class="fl"><p class="alert-danger" style="visibility:hidden">출발도시 코멘트입니다..</p></div>'
		+'<div class="fl"><p class="alert-danger" style="visibility:hidden">도착도시 코멘트입니다.</p></div>'
		+'<div class="fl"><p class="alert-danger" style="visibility:hidden">가는날 코멘트입니다.</p></div>'
		+'<div class="fl"><p class="alert-danger" style="visibility:hidden">오늘날 코멘트입니다.</p></div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'<div id="bx-pager02" class="bx-controls"></div>';
	},
	
	hotel_bottom:()=>{ 
		return '<div class="main-visual-02">'
		+'<div class="main-type">'
		+'<dl>'
		+'<dt><a href="javascript:void(0)">투어비스 프로모션</a></dt>'
		+'<dd>투어비스만의 엄선된<br>프로모션을 모아서 추천합니다.</dd>'
		+'</dl>'
		+'</div>'
		+'<div class="bx-wrapper" style="max-width: 100%;"><div class="bx-viewport" aria-live="polite" style="width: 100%; overflow: hidden; position: relative; height: 360px;"><div class="visual-promotion" id="mainBannerSlideB" style="width: 1215%; position: relative; transition-duration: 0s; transform: translate3d(-800px, 0px, 0px);"><div style="float: left; list-style: none; position: relative; width: 800px;" class="bx-clone" aria-hidden="true">'
		+'<ul>'
		+'<li class="">'
		+'<a href="https://air.tourvis.com/common/promotionWebView.lts?cSeq=50" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/UPLOAD/2019/04/03/icon_20190403182528185.png"></span>'
		+'<span class="tit">'
		+'미주 &amp; 캐나다 만나는<br>가장 빠른 방법, 에어캐나다'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">예약 기간 : <br> 2019. 04. 01 ~ 2019. 04. 30</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/airBoardList.lts?fnb_id=1369" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'무이자할부 안내'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">카드사별<br>무이자할부 안내</span>'
		+'</a>'
		+'</li>'
		+'<li class="">'
		+'<a href="http://air.tourvis.com/fr/common/airBoardList.lts" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'공지사항'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">투어비스의 새로운 소식과<br>공지사항 확인하기</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/findFaqList.lts?is_b2c=Y&amp;fqc_svc_type=AIR" target="_blank">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'고객센터'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">여행에 관한 모든 것<br>FAQ 자주묻는 질문 확인하기</span>'
		+'</a>'
		+'</li>'
		+'</ul>'
		+'</div>'
		+'<div style="float: left; list-style: none; position: relative; width: 800px;" aria-hidden="false">'
		+'<ul>'
		+'<li class="">'
		+'<a href="https://air.tourvis.com/common/promotionWebView.lts?cSeq=50" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/UPLOAD/2019/04/03/icon_20190403182528185.png"></span>'
		+'<span class="tit">'
		+'미주 &amp; 캐나다 만나는<br>가장 빠른 방법, 에어캐나다'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">예약 기간 : <br> 2019. 04. 01 ~ 2019. 04. 30</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/airBoardList.lts?fnb_id=1369" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'무이자할부 안내'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">카드사별<br>무이자할부 안내</span>'
		+'</a>'
		+'</li>'
		+'<li class="">'
		+'<a href="http://air.tourvis.com/fr/common/airBoardList.lts" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'공지사항'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">투어비스의 새로운 소식과<br>공지사항 확인하기</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/findFaqList.lts?is_b2c=Y&amp;fqc_svc_type=AIR" target="_blank">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'고객센터'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">여행에 관한 모든 것<br>FAQ 자주묻는 질문 확인하기</span>'
		+'</a>'
		+'</li>'
		+'</ul>'
		+'</div>'
		+'<div style="float: left; list-style: none; position: relative; width: 800px;" class="bx-clone" aria-hidden="true">'
		+'<ul>'
		+'<li class="">'
		+'<a href="https://air.tourvis.com/common/promotionWebView.lts?cSeq=50" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/UPLOAD/2019/04/03/icon_20190403182528185.png"></span>'
		+'<span class="tit">'
		+'미주 &amp; 캐나다 만나는<br>가장 빠른 방법, 에어캐나다'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">예약 기간 : <br> 2019. 04. 01 ~ 2019. 04. 30</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/airBoardList.lts?fnb_id=1369" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'무이자할부 안내'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">카드사별<br>무이자할부 안내</span>'
		+'</a>'
		+'</li>'
		+'<li class="">'
		+'<a href="http://air.tourvis.com/fr/common/airBoardList.lts" target="_self">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'공지사항'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">투어비스의 새로운 소식과<br>공지사항 확인하기</span>'
		+'</a>'
		+'</li>'
		+'<li class="even">'
		+'<a href="https://air.tourvis.com/fr/common/findFaqList.lts?is_b2c=Y&amp;fqc_svc_type=AIR" target="_blank">'
		+'<span class="air-logo"><img src="https://account.tourvis.com/static/img/upload/icon_tourvis.png"></span>'
		+'<span class="tit">'
		+'고객센터'
		+'</span>'
		+'<span class="sub"></span>'
		+'<span class="period">여행에 관한 모든 것<br>FAQ 자주묻는 질문 확인하기</span>'
		+'</a>'
		+'</li>'
		+'</ul>'
		+'</div></div></div><div class="bx-controls"></div></div>'
		+'<div id="bx-pager02" class="bx-controls"></div>'
		+'</div>'
	},
	hotel_search_result:()=>{ 
		return '<div id="hotel_clean" class="page white">'
	        +'    <div class="wrap">'
	        +'        <div class="page_title">'
	        +'            검색하신 호텔입니다.!        </div>'
	        +'        <div class="clear"></div>'
	        +'        <div class="intro_list">'
	        +'        </div>'
	        +'        <div class="clear"></div>'
	        +'    </div>'
	        +'</div>';
	    }
}